// bi-way-comm-react/src/messages.tsx
import { useState } from "react";
import Stack from '@mui/material/Stack';
import Button from '@mui/material/Button';

import './messages.css'
import { MessageList } from "./message_list";
import { MessageEditor } from "./edit_message";
import { Message } from "./model";


const EMPTY_MESSAGES : Message[] = []

function Messages () {
    const [messages, setMessages] = useState(EMPTY_MESSAGES)
    const [currentMsgId, setCurrentMsgId] = useState(-1)
    const [currentMessage, setCurrentMessage] = useState(new Message())
    // const [counter, setCounter] = useState(0)

    const saveMessage = (msg: Message | undefined) => {
        if (msg === undefined) {
            setCurrentMsgId(-1)
            setCurrentMessage(new Message())
        } else {
            console.log("addMessage", msg)
            // messages.push(msg)
            // setMessages([...messages, msg])
            // setCounter(counter + 1)
            // const currMsg = messages.find(msg => msg.id === msgId)
            setMessages(messages.map(m => m.id === msg.id ? msg : m))
            setCurrentMessage(msg)
        }
    }

    const processMessage = (msgId: number, action: string) => {
        console.log("processMessage", `action: ${action}`)
        if (action === 'delete') {
            setMessages(messages.filter( msg => msg.id !== msgId))
            setCurrentMsgId(-1)
        } else { // 'edit'
            setCurrentMsgId(msgId)
            const currMsg = messages.find(msg => msg.id === msgId)
            setCurrentMessage(currMsg === undefined ? new Message() : currMsg)
            // if (currMsg !== undefined) {
            //     setCurrentMessage(currMsg)
            //     console.log("processMessage", `currMessage = ${currMsg}`)
            //     // setTimeout( () => setCounter(counter + 1), 1000)
            // }
        }
    }

    const addMessage = () => {
        const msg = new Message()
        msg.id = messages.map( msg => msg.id).reduce ( (p, v) => p > v ? p : v, 0) + 1
        msg.subject = "Subject #" + msg.id
        msg.content = "Body #" + msg.id
        setMessages([...messages, msg])
    }

    return (
        <div className="messages">
            <div className="messages-header">Messages (total: {messages.length} messages)</div>
            <div className="messages-header-actions">
                <Stack spacing={2} direction="row">
                    {/* <Button variant="text" onClick={addMessage}>Create a new message</Button>
                    <Button variant="contained" onClick={addMessage}>Create a new message</Button> */}
                    <Button variant="contained" onClick={addMessage}>Create a new message</Button>
                </Stack>
            </div>
            <div className="messages-content">
                <div className="message-list">
                    <MessageList 
                        messages={messages} 
                        currentMessageId={currentMsgId} 
                        setCurrentMsgId={setCurrentMsgId} 
                        processMessage={processMessage}/>
                </div>
                <div className="message-editor">
                    {/* <MessageEditor message={messages.find(msg => msg.id === currentMsgId)} saveMessage={saveMessage}/> */}
                    <MessageEditor display={currentMsgId !== -1} enabled={currentMsgId !== -1}
                        message={currentMessage} saveMessage={saveMessage}/>
                </div>
            </div>
        </div>
    )
}

export {Messages}

// bi-way-comm-angular/src/app/messages.component.ts
import { Component, OnInit } from '@angular/core';
import {MatIconModule} from '@angular/material/icon';
import {MatDividerModule} from '@angular/material/divider';
import {MatButtonModule} from '@angular/material/button';
import { Message, EMPTY_MESSAGES, MessageAction } from './model';

@Component({
  selector: 'app-messages',
  templateUrl: './messages.component.html',
  styleUrls: ['./messages.component.css']
})

export class MessagesComponent implements OnInit {

  messages: Message[] = EMPTY_MESSAGES
  currentMsgId: number = -1
  currentMessage?: Message

  constructor() { }

  ngOnInit(): void {
  }

  addMessage () {
    const msg = new Message()
    msg.id = this.messages.map( msg => msg.id).reduce ( (p, v) => p > v ? p : v, 0) + 1
    msg.subject = "Subject #" + msg.id
    msg.content = "Body #" + msg.id
    // if (msg.id === 2) msg.subject += "aaaaaaaa"
    this.messages.push(msg)
    console.log("addMessage()", msg)
    
  }

  processMessage (messageAction: MessageAction) {
    console.log("processMessage", `action: ${messageAction.action} - ${messageAction.messageId}`)
    if (messageAction.action === 'delete') {
        this.messages = this.messages.filter( msg => msg.id !== messageAction.messageId)
        this.currentMsgId = -1
    } else { // 'edit'
      this.currentMsgId = messageAction.messageId
        this.currentMessage = this.messages.find(msg => msg.id === messageAction.messageId)

    }
  }

  saveMessage (msg?: Message) : void {
    if (msg) {
      console.log("saveMessage", msg)
      msg.timestamp = new Date()
      this.messages = this.messages.map(m => m.id === msg.id ? msg : m)
      this.currentMessage = msg
    } else {
      this.currentMsgId = -1
      this.currentMessage = undefined
    }
  }


}

<div class="messages">
    <div class="messages-header">Messages (total: {{messages.length}} messages)</div>
    <section>
        <div class="messages-header-actions">
          <button mat-raised-button color="primary" (click)="addMessage()">Create a new message</button>
        </div>
    </section>
    <mat-divider></mat-divider>
    <div class="messages-content">
        <div class="message-list">
            <app-message-list [messages]="messages" (messageActionEvent)="processMessage($event)"></app-message-list> 
        </div>
        <div class="message-editor">
            <app-message-editor [message]="currentMessage" (messageSaveEvent)="saveMessage($event)"></app-message-editor>
        </div>
    </div>
</div>
